import { NextApiRequest, NextApiResponse } from 'next';

interface BlogPostData {
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  readingTime: number;
}

interface DeepSeekResponse {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { topic, authorId, categoryId } = req.body;

  if (!topic || !authorId || !categoryId) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const deepSeekApiKey = process.env.DEEPSEEK_API_KEY;
  
  if (!deepSeekApiKey) {
    return res.status(500).json({ error: 'DeepSeek API key not configured' });
  }

  try {
    // Generate content with DeepSeek AI
    const deepSeekResponse = await fetch('https://api.deepseek.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${deepSeekApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          {
            role: 'system',
            content: 'You are an expert content writer specializing in compliance, whistleblowing, and corporate governance. Create engaging, SEO-optimized blog posts.'
          },
          {
            role: 'user',
            content: `Create a comprehensive blog post about "${topic}" for a whistleblowing and compliance platform. 

Requirements:
- Title: Catchy and SEO-friendly (50-60 characters)
- Slug: URL-friendly version of title (lowercase, hyphens)
- Content: Well-structured with headings, paragraphs (800-1200 words)
- Excerpt: Compelling summary (150-200 characters)
- SEO Title: Optimized for search engines (30-60 characters)
- SEO Description: Meta description (120-160 characters)
- Tags: 3-5 relevant tags
- Reading Time: Estimate in minutes

Format the response as JSON with this exact structure:
{
  "title": "Your Title Here",
  "slug": "your-slug-here",
  "content": "Your full blog content with proper HTML formatting",
  "excerpt": "Your compelling excerpt here",
  "seoTitle": "SEO Optimized Title",
  "seoDescription": "SEO meta description here",
  "tags": ["tag1", "tag2", "tag3"],
  "readingTime": 5
}`
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    });

    if (!deepSeekResponse.ok) {
      throw new Error(`DeepSeek API error: ${deepSeekResponse.statusText}`);
    }

    const deepSeekData: DeepSeekResponse = await deepSeekResponse.json();
    const generatedContent = deepSeekData.choices[0]?.message?.content;

    if (!generatedContent) {
      throw new Error('No content generated by DeepSeek');
    }

    // Parse the JSON response
    const jsonMatch = generatedContent.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON response from DeepSeek');
    }

    const blogData: BlogPostData = JSON.parse(jsonMatch[0]);

    // Prepare Contentful entry data
    const contentfulEntryData = {
      fields: {
        title: { 'en-US': blogData.title },
        slug: { 'en-US': blogData.slug },
        content: { 'en-US': blogData.content },
        excerpt: { 'en-US': blogData.excerpt },
        seoTitle: { 'en-US': blogData.seoTitle },
        seoDescription: { 'en-US': blogData.seoDescription },
        tags: { 'en-US': blogData.tags },
        readingTime: { 'en-US': blogData.readingTime },
        publishDate: { 'en-US': new Date().toISOString() },
        status: { 'en-US': 'draft' },
        author: { 'en-US': { sys: { id: authorId, linkType: 'Entry', type: 'Link' } } },
        categories: { 'en-US': [{ sys: { id: categoryId, linkType: 'Entry', type: 'Link' } }] }
      }
    };

    res.status(200).json({
      success: true,
      blogData,
      contentfulEntryData,
      message: 'Content generated successfully! Ready to create Contentful entry.'
    });

  } catch (error) {
    console.error('Error generating content:', error);
    res.status(500).json({ 
      error: 'Failed to generate content',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
}
