
import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Globe, CheckCircle, AlertCircle, Copy, ExternalLink, Info, AlertTriangle } from 'lucide-react';

interface DomainVerification {
  id: string;
  domain: string;
  verification_token: string;
  verification_type: string;
  verified_at: string | null;
  created_at: string;
}

interface CustomDomainSettingsProps {
  hasActiveTier2Subscription: boolean;
}

const CustomDomainSettings = ({ hasActiveTier2Subscription }: CustomDomainSettingsProps) => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [domainVerifications, setDomainVerifications] = useState<DomainVerification[]>([]);
  const [newDomain, setNewDomain] = useState('');
  const [showAddForm, setShowAddForm] = useState(false);

  useEffect(() => {
    if (user && hasActiveTier2Subscription) {
      fetchDomainVerifications();
    }
  }, [user, hasActiveTier2Subscription]);

  const fetchDomainVerifications = async () => {
    if (!user) return;

    try {
      const { data, error } = await supabase
        .from('domain_verifications')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setDomainVerifications(data || []);
    } catch (error: any) {
      console.error('Error fetching domain verifications:', error);
      toast({
        title: "Error fetching domains",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const addDomain = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !newDomain.trim()) return;

    // Basic domain validation
    const domainRegex = /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/;
    if (!domainRegex.test(newDomain)) {
      toast({
        title: "Invalid domain",
        description: "Please enter a valid domain name (e.g., reports.yourcompany.com)",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      // Get user's organization
      const { data: profile } = await supabase
        .from('profiles')
        .select('organization_id')
        .eq('id', user.id)
        .single();

      if (!profile?.organization_id) {
        throw new Error('Organization not found');
      }

      const { error } = await supabase
        .from('domain_verifications')
        .insert({
          organization_id: profile.organization_id,
          domain: newDomain.toLowerCase(),
          verification_type: 'CNAME',
          verification_token: '' // This will be auto-generated by the database trigger
        });

      if (error) throw error;

      toast({
        title: "Domain added successfully",
        description: "Please configure the DNS settings to verify your domain.",
      });

      setNewDomain('');
      setShowAddForm(false);
      fetchDomainVerifications();
    } catch (error: any) {
      console.error('Error adding domain:', error);
      toast({
        title: "Error adding domain",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: `${label} copied!`,
      description: "The value has been copied to your clipboard.",
    });
  };

  const verifyDomain = async (domainId: string) => {
    setLoading(true);
    try {
      // In a real implementation, this would check DNS records
      // For now, we'll simulate verification
      const { error } = await supabase
        .from('domain_verifications')
        .update({ verified_at: new Date().toISOString() })
        .eq('id', domainId);

      if (error) throw error;

      toast({
        title: "Domain verified!",
        description: "Your custom domain verification is complete. Contact support to enable routing.",
      });

      fetchDomainVerifications();
    } catch (error: any) {
      console.error('Error verifying domain:', error);
      toast({
        title: "Verification failed",
        description: "Please check your DNS settings and try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  if (!hasActiveTier2Subscription) {
    return (
      <Card className="border-amber-200 bg-amber-50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Globe className="h-5 w-5" />
            Custom Domain Branding
          </CardTitle>
          <CardDescription>
            Use your own domain for submission links (Tier 2 feature)
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-gray-600 mb-4">
            Upgrade to Tier 2 to use your own custom domain for your submission links, 
            giving your reports a more professional and branded appearance.
          </p>
          <Badge variant="secondary">Tier 2 Required</Badge>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex justify-between items-start">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Globe className="h-5 w-5" />
                Custom Domain Branding
              </CardTitle>
              <CardDescription>
                Set up your custom domain for branded submission links
              </CardDescription>
            </div>
            <Button onClick={() => setShowAddForm(!showAddForm)}>
              Add Domain
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {/* Important Server Configuration Notice */}
          <div className="mb-6 p-4 bg-orange-50 rounded-lg border border-orange-200">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-orange-600 mt-0.5 flex-shrink-0" />
              <div className="text-sm">
                <h4 className="font-medium text-orange-900 mb-2">Server Configuration Required</h4>
                <div className="text-orange-800 space-y-2">
                  <p>Custom domain routing requires server-side configuration that cannot be automated through DNS alone.</p>
                  <p><strong>After DNS verification:</strong></p>
                  <ul className="list-disc ml-4 space-y-1">
                    <li>Contact our support team to enable custom domain routing</li>
                    <li>We'll configure the necessary server infrastructure</li>
                    <li>Your links will then work with your custom domain</li>
                  </ul>
                  <p className="text-sm mt-2">
                    <strong>Contact:</strong> support@disclosurely.com with your verified domain
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* DNS Setup Information */}
          <div className="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
              <div className="text-sm">
                <h4 className="font-medium text-blue-900 mb-2">How Custom Domain Setup Works</h4>
                <ol className="text-blue-800 space-y-1 list-decimal ml-4">
                  <li>Add your custom domain below</li>
                  <li>Configure DNS CNAME records as instructed</li>
                  <li>Verify domain ownership</li>
                  <li>Contact support to enable server-side routing</li>
                  <li>Your submission links will use your custom domain</li>
                </ol>
              </div>
            </div>
          </div>

          {showAddForm && (
            <form onSubmit={addDomain} className="mb-6 p-4 border rounded-lg bg-gray-50">
              <div className="space-y-4">
                <div>
                  <Label htmlFor="domain">Custom Domain</Label>
                  <Input
                    id="domain"
                    value={newDomain}
                    onChange={(e) => setNewDomain(e.target.value)}
                    placeholder="reports.yourcompany.com"
                    required
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Enter the subdomain you want to use (e.g., reports.yourcompany.com)
                  </p>
                </div>
                <div className="flex space-x-2">
                  <Button type="submit" disabled={loading}>
                    {loading ? 'Adding...' : 'Add Domain'}
                  </Button>
                  <Button type="button" variant="outline" onClick={() => setShowAddForm(false)}>
                    Cancel
                  </Button>
                </div>
              </div>
            </form>
          )}

          {domainVerifications.length === 0 ? (
            <div className="text-center py-8">
              <Globe className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">No custom domains yet</h3>
              <p className="text-gray-600">
                Add a custom domain to brand your submission links with your own domain.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {domainVerifications.map((domain) => (
                <Card key={domain.id} className="border-l-4 border-l-blue-500">
                  <CardContent className="pt-6">
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <h4 className="font-medium text-lg">{domain.domain}</h4>
                        <div className="flex items-center gap-2 mt-1">
                          {domain.verified_at ? (
                            <Badge variant="default" className="bg-green-100 text-green-800">
                              <CheckCircle className="h-3 w-3 mr-1" />
                              DNS Verified
                            </Badge>
                          ) : (
                            <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">
                              <AlertCircle className="h-3 w-3 mr-1" />
                              DNS Configuration Required
                            </Badge>
                          )}
                        </div>
                      </div>
                      {!domain.verified_at && (
                        <Button onClick={() => verifyDomain(domain.id)} disabled={loading}>
                          Check Verification
                        </Button>
                      )}
                    </div>

                    {!domain.verified_at && (
                      <div className="space-y-4 bg-blue-50 p-4 rounded-lg">
                        <h5 className="font-medium text-blue-900">DNS Configuration Required</h5>
                        <p className="text-sm text-blue-800">
                          Add these CNAME records to your DNS settings:
                        </p>
                        
                        <div className="space-y-3">
                          {/* Main CNAME for the domain */}
                          <div className="bg-white p-3 rounded border">
                            <Label className="text-xs font-medium text-gray-500">CNAME RECORD #1 - Main Domain</Label>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-2">
                              <div>
                                <Label className="text-xs text-gray-500">NAME/HOST:</Label>
                                <div className="flex items-center justify-between">
                                  <code className="text-sm bg-gray-100 px-2 py-1 rounded">{domain.domain.split('.')[0]}</code>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => copyToClipboard(domain.domain.split('.')[0], 'CNAME name')}
                                  >
                                    <Copy className="h-3 w-3" />
                                  </Button>
                                </div>
                              </div>
                              <div>
                                <Label className="text-xs text-gray-500">VALUE/TARGET:</Label>
                                <div className="flex items-center justify-between">
                                  <code className="text-sm bg-gray-100 px-2 py-1 rounded">cname.disclosurely.com</code>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => copyToClipboard('cname.disclosurely.com', 'CNAME target')}
                                  >
                                    <Copy className="h-3 w-3" />
                                  </Button>
                                </div>
                              </div>
                              <div>
                                <Label className="text-xs text-gray-500">TTL:</Label>
                                <code className="text-sm bg-gray-100 px-2 py-1 rounded">300</code>
                              </div>
                            </div>
                          </div>

                          {/* Verification CNAME */}
                          <div className="bg-white p-3 rounded border">
                            <Label className="text-xs font-medium text-gray-500">CNAME RECORD #2 - Verification</Label>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-2">
                              <div>
                                <Label className="text-xs text-gray-500">NAME/HOST:</Label>
                                <div className="flex items-center justify-between">
                                  <code className="text-sm bg-gray-100 px-2 py-1 rounded">_verify.{domain.domain.split('.')[0]}</code>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => copyToClipboard(`_verify.${domain.domain.split('.')[0]}`, 'Verification name')}
                                  >
                                    <Copy className="h-3 w-3" />
                                  </Button>
                                </div>
                              </div>
                              <div>
                                <Label className="text-xs text-gray-500">VALUE/TARGET:</Label>
                                <div className="flex items-center justify-between">
                                  <code className="text-sm bg-gray-100 px-2 py-1 rounded">{domain.verification_token}.verify.disclosurely.com</code>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => copyToClipboard(`${domain.verification_token}.verify.disclosurely.com`, 'Verification target')}
                                  >
                                    <Copy className="h-3 w-3" />
                                  </Button>
                                </div>
                              </div>
                              <div>
                                <Label className="text-xs text-gray-500">TTL:</Label>
                                <code className="text-sm bg-gray-100 px-2 py-1 rounded">300</code>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div className="text-xs text-blue-700 space-y-1">
                          <p><strong>Step-by-step:</strong></p>
                          <p>1. Log in to your domain registrar (GoDaddy, Namecheap, Cloudflare, etc.)</p>
                          <p>2. Find DNS management or DNS settings</p>
                          <p>3. Add both CNAME records exactly as shown above</p>
                          <p>4. Wait 5-10 minutes, then click "Check Verification"</p>
                          <p><strong>Note:</strong> DNS changes can take up to 24 hours to fully propagate</p>
                        </div>
                      </div>
                    )}

                    {domain.verified_at && (
                      <div className="bg-green-50 p-4 rounded-lg">
                        <div className="flex items-center gap-2 mb-2">
                          <CheckCircle className="h-4 w-4 text-green-600" />
                          <span className="text-green-800 font-medium">DNS Verified - Server Setup Required</span>
                        </div>
                        <p className="text-sm text-green-700 mb-3">
                          Your DNS is configured correctly! To complete the setup:
                        </p>
                        <div className="bg-white p-3 rounded border border-green-200 space-y-2">
                          <p className="text-sm font-medium text-green-800">Next Steps:</p>
                          <ol className="text-sm text-green-700 list-decimal ml-4 space-y-1">
                            <li>Contact our support team at <strong>support@disclosurely.com</strong></li>
                            <li>Include your verified domain: <strong>{domain.domain}</strong></li>
                            <li>We'll configure server-side routing within 24-48 hours</li>
                            <li>Your submission links will then work with your custom domain</li>
                          </ol>
                        </div>
                        <p className="text-xs text-green-600 mt-2">
                          Expected URL format: https://{domain.domain}/secure/tool/submit/[link-id]
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default CustomDomainSettings;
